-- 添加 MVIP、称号相关字段到 users 表
ALTER TABLE users ADD COLUMN isMvip INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN mvipExpire DATETIME;
ALTER TABLE users ADD COLUMN title TEXT;
ALTER TABLE users ADD COLUMN showTitle INTEGER DEFAULT 0;
